apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-config
data:
  peeling_example.yaml: |
    apiVersion: RedirectionService/v1
    kind: ParamPeelingConfig
    metadata:
      name: "example_config"
    spec:
        hosts: ["888casino.com", "888poker.com", "10.20.35.111:30004"]
        protocols: ["http", "https"]
        params: [
            "ftd",
            "lang"
        ]
  redirections_example.yml: |
    apiVersion: RedirectionService/v1
    kind: RedirectionsConfig
    metadata:
      name: "RedirectionsConfigExample"
    spec:
      hosts: ["888casino.com", "888poker.com", "10.20.35.111:30004"]
      protocols: ["http", "https"]
      rules:
        - type: "Hash"
          fileUrl: "hash.csv"
        - type: "Hash"
          targetsByURL:
            - src: https://888casino.com/blog
              target: https://newblog.888casino.com/
              httpStatusCode: 302
            - src: https://888sport.com/blog
              target: https://newblog.888sport.com/
              httpStatusCode: 302
            - src: http://10.20.35.111:30004/test
              target: https://www.888casino.com/blog/
              httpStatusCode: 302
        - type: "Regexp"
          regexExpression: "http(s?):\\/\\/10.20.35.111:30004\\/blog(.*)"
          target: https://newblog.888sport.com/
          httpStatusCode: 302
        # - type: "CustomLogic"
        #   logicName: "MyFunctionName"
